import {useState} from "react";import {useParams} from "react-router-dom";import Shell from "../components/Shell";import {api} from "../api";
export default function Ghostwriter(){const {projectId=""}=useParams(),[instruction,setInstruction]=useState(""),[draft,setDraft]=useState<any>(),[content,setContent]=useState(""),
[version,setVersion]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
async function generate(){setBusy(true);try{const d=await api.draft(projectId,{channel:"whatsapp",recipient_role:"provider",intent:"follow_up",instruction,
voice_profile_id:"pending_external",source_refs:[]});setDraft(d);setContent(d.draft);setVersion(d.draft_version_id);setStatus("")}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
async function edit(){const v=await api.editDraft(projectId,draft.draft_id,content);setVersion(v.id);setStatus(`Versão ${v.version} salva. Aprovações anteriores invalidadas.`)}
async function request(){await api.requestApproval(projectId,draft.draft_id,version);setStatus("Aguardando aprovação humana.")}
async function approve(){const a=await api.approve(projectId,draft.draft_id,version);setStatus(`Versão aprovada. ApprovedVersion ${a.approved_version_id.slice(0,8)} · candidato de memória ${a.memory_candidate_id.slice(0,8)} criado, ainda inativo.`)}
return <Shell><div className="page-head"><div><span className="section-kicker">HYPER SABRINA • GHOSTWRITER</span><h1>Comunicação com contexto.</h1><p>Elegante, inspiradora e sempre em modo rascunho.</p></div><span className="guard">DRAFT ONLY</span></div>
<div className="ghost-layout"><section className="glass panel"><label>O que você precisa comunicar?</label><textarea rows={8} value={instruction} onChange={e=>setInstruction(e.target.value)}
placeholder="Ex.: solicitar retorno do fornecedor sobre a iluminação, com firmeza e elegância."/><button disabled={!instruction.trim()||busy} onClick={generate} className="button primary wide">{busy?"Construindo contexto…":"Criar rascunho governado"}</button></section>
<section className="glass panel"><small className="gold">RASCUNHO PARA APROVAÇÃO DA SABRINA</small>{draft?<><textarea rows={12} value={content} onChange={e=>setContent(e.target.value)}/>
<div className="risk-list">{draft.risk_flags?.length?draft.risk_flags.map((f:any)=><div className={`risk ${f.severity.toLowerCase()}`} key={f.code}><b>{f.severity}</b><span>{f.code}</span><small>{f.evidence}</small></div>):<div className="risk low"><b>LOW</b><span>Nenhum gate sensível detectado</span></div>}</div>
<div className="approval-actions"><button className="button ghost" onClick={edit}>Salvar nova versão</button><button className="button ghost" onClick={request}>Solicitar aprovação</button><button className="button primary" onClick={approve}>Aprovar versão</button></div></>:<div className="empty">O rascunho aparecerá aqui com riscos e trilha de aprovação.</div>}
{status&&<div className="notice">{status}</div>}</section></div><div className="governance"><span>✓ tenant explícito</span><span>✓ contexto versionado</span><span>✓ risk scan</span><span>✓ external_write=false</span><span>✓ aprovação SHA-256</span></div></Shell>}
